GET http://localhost:3000/players/
###

GET http://localhost:3000/players/5/
###

PUT http://localhost:3000/players/5/
Content-Type: application/json

{
  "playerName": "Sravan Kumar Samala"
}
###

GET http://localhost:3000/matches/6/